name: Test Detectors

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/cargo-scout-audit/**"
      - "detectors/**"
      - "test-cases/**"
      - "Makefile"
  pull_request:
    paths:
      - "apps/cargo-scout-audit/**"
      - "detectors/**"
      - "test-cases/**"
      - "Makefile"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache cargo-scout dependencies
        id: cache-cargo-scout-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            apps/cargo-scout-audit/target
            detectors/target
            detectors/Cargo.lock
          key: ${{ runner.os }}-cargo-scout-dependencies-${{ github.run_id }}

      - name: Install Rust nightly-2023-09-29
        run: rustup install nightly-2023-09-29 --profile minimal

      - name: Install dylint-link
        run: cargo install dylint-link

      - name: Compile cargo-scout-audit tests
        working-directory: apps/cargo-scout-audit
        run: cargo test --no-run

      - name: Compile detectors
        working-directory: detectors
        run: cargo build --release

  test:
    name: Test
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        test:
          [
            "soroban-version",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache cargo-scout dependencies
        id: cache-cargo-scout-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            apps/cargo-scout-audit/target
            detectors/target
            detectors/Cargo.lock
          key: ${{ runner.os }}-cargo-scout-dependencies-${{ github.run_id  }}
          fail-on-cache-miss: true

      - name: Run tests
        working-directory: apps/cargo-scout-audit
        env:
          INTEGRATION_TESTS_TO_RUN: ${{ matrix.test }}
        run: cargo test -- --nocapture
